apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  replicas: 6
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: client
    spec:
      containers:
      - env:
        - name: CLIENT_IMAGE
          value: adnanrahic/smoketest
        - name: GET_HOSTS_FROM
          value: dns
        image: client
        name: client
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
