version: "3"
services:
  mongo:
    environment:
      - GET_HOSTS_FROM=dns
    image: mongo
    labels:
      kompose.volume.size: 1Gi
    volumes:
      - mongo:/data/db
    
  api:
    environment:
      - SECRET=secretkey
      - NODE_ENV=prod
      - DB=mongodb://mongo:27017/boilerplate_api
      - PORT=3000
      - GET_HOSTS_FROM=dns
    image: adnanrahic/boilerplate-api
    deploy:
      replicas: 1
    ports:
      - "3000"
    labels:
      kompose.service.type: LoadBalancer

  client:
    environment:
      - GET_HOSTS_FROM=dns
    image: adnanrahic/smoketest
    deploy:
      replicas: 1
    ports:
      - "80:80"
    labels:
      kompose.service.type: LoadBalancer

volumes:
  mongo:


