version: "3"
services:
  redis:
    image: redis:alpine
    volumes:
      - db-data:/data
    networks: 
      skynet:
        aliases:
          - db
    deploy:
      placement:
        constraint: [node.role == manager]
  
  web:
    image: katacode/redis-node-docker-example
    networks: 
      - skynet
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP=WEB]
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      placement:
        constraints: [node.role == worker]

networks: 
  skynet:

volumes:
  db-data: