version: "3"
services:
  mongo:
    image: mongo:4.0
    volumes:
      - mongo:/data/db
    networks: 
      backend:
        aliases:
          - mongo
  
  api:
    env_file:
      - test.variables.env
    build:
      context: ./
      dockerfile: Dockerfile.test-integration
    image: "${API_IMAGE}"
    volumes:
      - ./logs:/usr/src/app/logs
    networks: 
      backend:
        aliases:
          - api
      frontend:
        aliases:
          - api 
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: "${CLIENT_IMAGE}"
    networks: 
      - frontend
    depends_on:
      - api
    ports:
      - "80:80"

networks: 
  backend:
  frontend:

volumes:
  mongo: