apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-kompose.yml
    kompose.version: 1.1.0 (36652f6)
    kompose.volume.size: 1Gi
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: mongo
status:
  loadBalancer: {}
