apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f docker-kompose.yml convert
    kompose.version: 1.1.0 (36652f6)
    kompose.volume.size: 1Gi
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: mongo
status:
  loadBalancer: {}
